import { Inter } from "next/font/google";
import "./globals.css";
import Script from 'next/script'
import { getTokens } from "next-firebase-auth-edge";
import { cookies } from "next/headers";
import { authConfig } from "../config/auth/server-config";
import { CustomAuthProvider } from "../context/AuthContext";
import { toUser } from "../helper/user";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "GenAI Tools",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const tokens = await getTokens(cookies(), authConfig);
  const user = tokens ? toUser(tokens) : null;
  return (
    <html lang="en">
      <Script type="module" src="https://unpkg.com/@google/model-viewer/dist/model-viewer.min.js"></Script>
      <Script src="https://unpkg.com/@dotlottie/player-component@latest/dist/dotlottie-player.mjs" type="module"></Script>
      <body className={inter.className}>
      <CustomAuthProvider user={user}>
        {children}
        </CustomAuthProvider>
        </body>
    </html>
  );
}
